blank_issues_enabled: false
contact_links:
  - name: Q&A / Usage questions
    url: https://github.com/hngpham/stock-alerts/discussions/new?category=q-a
    about: Ask “how do I …” and setup questions here.
